sys:1: DtypeWarning: Columns (13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,172,1790,1941,1942,1943,1944,1945,1946,1947,1948,1949,1973,1974,1975,1976,1977,1978,1979,1980,1981,2031,2032,2033,2034,2035,2036,2037,2038,2039,2062,2063,2064,2065,2066,2067,2068,2069,2070,2088,2094,2095,2096,2097,2098,2099,2100,2101,2102,2126,2127,2128,2129,2130,2131,2132,2133,2134,2160,2161,2162,2163,2164,2165,2166,2167,2168,2194,2195,2196,2197,2198,2199,2200,2201,2202,2228,2229,2230,2231,2232,2233,2234,2235,2236,2262,2263,2264,2265,2266,2267,2268,2269,2270,2296,2297,2298,2299,2300,2301,2302,2303,2304,2330,2331,2332,2333,2334,2335,2336,2337,2338,2363,2364,2365,2366,2367,2368,2369,2370,2371,2396,2397,2398,2399,2400,2401,2402,2403,2404,2429,2430,2431,2432,2433,2434,2435,2436,2437,2462,2463,2464,2465,2466,2467,2468,2469,2470,2495,2496,2497,2498,2499,2500,2501,2502,2503,2533,5462,5463,5464) have mixed types. Specify dtype option on import or set low_memory=False.
Traceback (most recent call last):
  File "convert_csv_to_h5.py", line 65, in <module>
    save_to_hdf5(pd.read_csv(args.i, keep_default_na=False), args.o)
  File "convert_csv_to_h5.py", line 22, in save_to_hdf5
    output_file.create_group('/')
  File "/home/wdjo224/miniconda3/envs/protein_binding/lib/python3.6/site-packages/h5py/_hl/group.py", line 52, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/_objects.c:2804)
  File "h5py/h5g.pyx", line 151, in h5py.h5g.create (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/h5g.c:2929)
ValueError: Unable to create group (Name already exists)
